# Generated by Django 3.1 on 2020-08-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sci_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('water', models.TextField(max_length=250)),
                ('sun', models.TextField(max_length=250)),
                ('food', models.TextField(max_length=250)),
                ('toxicity', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
