# Generated by Django 3.1 on 2020-08-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='genus',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
