# Generated by Django 3.1 on 2020-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200826_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('locaation', models.TextField(max_length=250)),
            ],
        ),
    ]
