# Generated by Django 3.1 on 2020-09-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200829_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.CharField(max_length=15)),
                ('watering', models.CharField(choices=[('M', 'Morning Water'), ('A', 'Afternoon Water'), ('E', 'Evening Water')], default='M', max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.CharField(max_length=15)),
                ('Feeding', models.CharField(choices=[('C', 'Compost Tea'), ('F', 'Fertilizer'), ('S', 'New Soil')], default='C', max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
