# Generated by Django 3.1 on 2020-09-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_feeding_watering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='Feeding',
            new_name='feeding',
        ),
    ]
